// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -finclude-default-header -fnative-half-type -fnative-int16-type -triple dxil-pc-shadermodel6.3-library -x hlsl -emit-llvm -disable-llvm-passes -o - %s | FileCheck %s

struct S {
  int X;
  float Y;
};

// CHECK-LABEL: define hidden void @_Z5call0v(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NEXT:    [[A:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[S]], ptr align 1 @__const._Z5call0v.s, i32 8, i1 false)
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[AGG_TEMP]], ptr align 1 [[S]], i32 8, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[GEP]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
// CHECK-NEXT:    ret void
//
void call0() {
  S s = {1,2};
  int A = (int)s;
}

// struct from vector
// CHECK-LABEL: define hidden void @_Z5call1v(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A:%.*]] = alloca <2 x i32>, align 4
// CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NEXT:    store <2 x i32> <i32 1, i32 2>, ptr [[A]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i32>, ptr [[A]], align 4
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[VEC_LOAD:%.*]] = extractelement <2 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    store i32 [[VEC_LOAD]], ptr [[GEP]], align 4
// CHECK-NEXT:    [[VEC_LOAD2:%.*]] = extractelement <2 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[VEC_LOAD2]] to float
// CHECK-NEXT:    store float [[CONV]], ptr [[GEP1]], align 4
// CHECK-NEXT:    [[X:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-NEXT:    [[X3:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X3]], align 1
// CHECK-NEXT:    store i32 [[TMP1]], ptr [[X]], align 1
// CHECK-NEXT:    [[Y:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-NEXT:    [[Y4:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[Y4]], align 1
// CHECK-NEXT:    store float [[TMP2]], ptr [[Y]], align 1
// CHECK-NEXT:    ret void
//
void call1() {
  int2 A = {1,2};
  S s = (S)A;
}


// struct from array
// CHECK-LABEL: define hidden void @_Z5call2v(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A:%.*]] = alloca [2 x i32], align 4
// CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [2 x i32], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[A]], ptr align 4 @__const._Z5call2v.A, i32 8, i1 false)
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[AGG_TEMP]], ptr align 4 [[A]], i32 8, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [2 x i32], ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [2 x i32], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[GEP2]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[GEP3]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[TMP1]] to float
// CHECK-NEXT:    store float [[CONV]], ptr [[GEP1]], align 4
// CHECK-NEXT:    [[X:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-NEXT:    [[X4:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X4]], align 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 1
// CHECK-NEXT:    [[Y:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-NEXT:    [[Y5:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y5]], align 1
// CHECK-NEXT:    store float [[TMP3]], ptr [[Y]], align 1
// CHECK-NEXT:    ret void
//
void call2() {
  int A[2] = {1,2};
  S s = (S)A;
}

struct Q {
  int Z;
};

struct R {
  Q q;
  float F;
};

// struct from nested struct?
// CHECK-LABEL: define hidden void @_Z5call6v(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[R:%.*]] = alloca [[STRUCT_R:%.*]], align 1
// CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [[STRUCT_R]], align 1
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[R]], ptr align 1 @__const._Z5call6v.r, i32 8, i1 false)
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[AGG_TEMP]], ptr align 1 [[R]], i32 8, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_R]], ptr [[AGG_TEMP]], i32 0, i32 0, i32 0
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [[STRUCT_R]], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[GEP2]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[GEP3]], align 4
// CHECK-NEXT:    store float [[TMP1]], ptr [[GEP1]], align 4
// CHECK-NEXT:    [[X:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-NEXT:    [[X4:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X4]], align 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 1
// CHECK-NEXT:    [[Y:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-NEXT:    [[Y5:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y5]], align 1
// CHECK-NEXT:    store float [[TMP3]], ptr [[Y]], align 1
// CHECK-NEXT:    ret void
//
void call6() {
  R r = {{1}, 2.0};
  S s = (S)r;
}

// nested struct from array?
//
// CHECK-LABEL: define hidden void @_Z5call7v(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A:%.*]] = alloca [2 x i32], align 4
// CHECK-NEXT:    [[R:%.*]] = alloca [[STRUCT_R:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_R]], align 1
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [2 x i32], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[A]], ptr align 4 @__const._Z5call7v.A, i32 8, i1 false)
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 4 [[AGG_TEMP]], ptr align 4 [[A]], i32 8, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_R]], ptr [[REF_TMP]], i32 0, i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_R]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [2 x i32], ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [2 x i32], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[GEP2]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[GEP3]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[TMP1]] to float
// CHECK-NEXT:    store float [[CONV]], ptr [[GEP1]], align 4
// CHECK-NEXT:    [[Q:%.*]] = getelementptr inbounds nuw [[STRUCT_R]], ptr [[R]], i32 0, i32 0
// CHECK-NEXT:    [[Z:%.*]] = getelementptr inbounds nuw [[STRUCT_Q:%.*]], ptr [[Q]], i32 0, i32 0
// CHECK-NEXT:    [[Q4:%.*]] = getelementptr inbounds nuw [[STRUCT_R]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[Z5:%.*]] = getelementptr inbounds nuw [[STRUCT_Q]], ptr [[Q4]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[Z5]], align 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[Z]], align 1
// CHECK-NEXT:    [[F:%.*]] = getelementptr inbounds nuw [[STRUCT_R]], ptr [[R]], i32 0, i32 1
// CHECK-NEXT:    [[F6:%.*]] = getelementptr inbounds nuw [[STRUCT_R]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[F6]], align 1
// CHECK-NEXT:    store float [[TMP3]], ptr [[F]], align 1
// CHECK-NEXT:    ret void
//
void call7() {
  int A[2] = {1,2};
  R r = (R)A;
}

struct T {
  int A;
  int B;
  int C;
};

// struct truncation
// CHECK-LABEL: define hidden void @_Z5call8v(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[T:%.*]] = alloca [[STRUCT_T:%.*]], align 1
// CHECK-NEXT:    [[S:%.*]] = alloca [[STRUCT_S:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_S]], align 1
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [[STRUCT_T]], align 1
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[T]], ptr align 1 @__const._Z5call8v.t, i32 12, i1 false)
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[AGG_TEMP]], ptr align 1 [[T]], i32 12, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_T]], ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [[STRUCT_T]], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds [[STRUCT_T]], ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[GEP2]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[GEP3]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[TMP1]] to float
// CHECK-NEXT:    store float [[CONV]], ptr [[GEP1]], align 4
// CHECK-NEXT:    [[X:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 0
// CHECK-NEXT:    [[X5:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X5]], align 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[X]], align 1
// CHECK-NEXT:    [[Y:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[S]], i32 0, i32 1
// CHECK-NEXT:    [[Y6:%.*]] = getelementptr inbounds nuw [[STRUCT_S]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y6]], align 1
// CHECK-NEXT:    store float [[TMP3]], ptr [[Y]], align 1
// CHECK-NEXT:    ret void
//
void call8() {
  T t = {1,2,3};
  S s = (S)t;
}

struct BFields {
  double D;
  int E: 15;
  int : 8;
  float F;
};

struct Derived : BFields {
  int G;
};

// Derived Struct truncate to scalar
// CHECK-LABEL: define hidden void @_Z5call97Derived(
// CHECK-SAME: ptr noundef dead_on_return [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[D_INDIRECT_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[D2:%.*]] = alloca double, align 8
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [[STRUCT_DERIVED:%.*]], align 1
// CHECK-NEXT:    store ptr [[D]], ptr [[D_INDIRECT_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[AGG_TEMP]], ptr align 1 [[D]], i32 19, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[E:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS:%.*]], ptr [[GEP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 0, i32 0
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 0, i32 2
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[GEP1]], align 8
// CHECK-NEXT:    store double [[TMP0]], ptr [[D2]], align 8
// CHECK-NEXT:    ret void
//
void call9(Derived D) {
  double D2 = (double)D;
}

// Derived struct from vector
// CHECK-LABEL: define hidden void @_Z6call10Dv4_i(
// CHECK-SAME: <4 x i32> noundef [[I:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[I_ADDR:%.*]] = alloca <4 x i32>, align 4
// CHECK-NEXT:    [[D:%.*]] = alloca [[STRUCT_DERIVED:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_DERIVED]], align 1
// CHECK-NEXT:    store <4 x i32> [[I]], ptr [[I_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[I_ADDR]], align 4
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[E:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS:%.*]], ptr [[GEP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[REF_TMP]], i32 0, i32 0, i32 0
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[REF_TMP]], i32 0, i32 0, i32 2
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[VEC_LOAD:%.*]] = extractelement <4 x i32> [[TMP0]], i64 0
// CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[VEC_LOAD]] to double
// CHECK-NEXT:    store double [[CONV]], ptr [[GEP1]], align 8
// CHECK-NEXT:    [[VEC_LOAD4:%.*]] = extractelement <4 x i32> [[TMP0]], i64 1
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[VEC_LOAD4]] to i24
// CHECK-NEXT:    [[BF_LOAD:%.*]] = load i24, ptr [[E]], align 1
// CHECK-NEXT:    [[BF_VALUE:%.*]] = and i24 [[TMP1]], 32767
// CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i24 [[BF_LOAD]], -32768
// CHECK-NEXT:    [[BF_SET:%.*]] = or i24 [[BF_CLEAR]], [[BF_VALUE]]
// CHECK-NEXT:    store i24 [[BF_SET]], ptr [[E]], align 1
// CHECK-NEXT:    [[VEC_LOAD5:%.*]] = extractelement <4 x i32> [[TMP0]], i64 2
// CHECK-NEXT:    [[CONV6:%.*]] = sitofp i32 [[VEC_LOAD5]] to float
// CHECK-NEXT:    store float [[CONV6]], ptr [[GEP2]], align 4
// CHECK-NEXT:    [[VEC_LOAD7:%.*]] = extractelement <4 x i32> [[TMP0]], i64 3
// CHECK-NEXT:    store i32 [[VEC_LOAD7]], ptr [[GEP3]], align 4
// CHECK-NEXT:    [[D8:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[D]], i32 0, i32 0
// CHECK-NEXT:    [[D9:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[D9]], align 1
// CHECK-NEXT:    store double [[TMP2]], ptr [[D8]], align 1
// CHECK-NEXT:    [[E10:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[D]], i32 0, i32 1
// CHECK-NEXT:    [[E11:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[BF_LOAD12:%.*]] = load i24, ptr [[E11]], align 1
// CHECK-NEXT:    [[BF_SHL:%.*]] = shl i24 [[BF_LOAD12]], 9
// CHECK-NEXT:    [[BF_ASHR:%.*]] = ashr i24 [[BF_SHL]], 9
// CHECK-NEXT:    [[BF_CAST:%.*]] = sext i24 [[BF_ASHR]] to i32
// CHECK-NEXT:    [[TMP3:%.*]] = trunc i32 [[BF_CAST]] to i24
// CHECK-NEXT:    [[BF_LOAD13:%.*]] = load i24, ptr [[E10]], align 1
// CHECK-NEXT:    [[BF_VALUE14:%.*]] = and i24 [[TMP3]], 32767
// CHECK-NEXT:    [[BF_CLEAR15:%.*]] = and i24 [[BF_LOAD13]], -32768
// CHECK-NEXT:    [[BF_SET16:%.*]] = or i24 [[BF_CLEAR15]], [[BF_VALUE14]]
// CHECK-NEXT:    store i24 [[BF_SET16]], ptr [[E10]], align 1
// CHECK-NEXT:    [[F:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[D]], i32 0, i32 2
// CHECK-NEXT:    [[F17:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 2
// CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[F17]], align 1
// CHECK-NEXT:    store float [[TMP4]], ptr [[F]], align 1
// CHECK-NEXT:    [[G:%.*]] = getelementptr inbounds nuw [[STRUCT_DERIVED]], ptr [[D]], i32 0, i32 1
// CHECK-NEXT:    [[G18:%.*]] = getelementptr inbounds nuw [[STRUCT_DERIVED]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[G18]], align 1
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[G]], align 1
// CHECK-NEXT:    ret void
//
void call10(int4 I) {
  Derived D = (Derived)I;
}

// truncate derived struct
// CHECK-LABEL: define hidden void @_Z6call117Derived(
// CHECK-SAME: ptr noundef dead_on_return [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[D_INDIRECT_ADDR:%.*]] = alloca ptr, align 4
// CHECK-NEXT:    [[B:%.*]] = alloca [[STRUCT_BFIELDS:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_BFIELDS]], align 1
// CHECK-NEXT:    [[AGG_TEMP:%.*]] = alloca [[STRUCT_DERIVED:%.*]], align 1
// CHECK-NEXT:    store ptr [[D]], ptr [[D_INDIRECT_ADDR]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[AGG_TEMP]], ptr align 1 [[D]], i32 19, i1 false)
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0
// CHECK-NEXT:    [[E:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[GEP]], i32 0, i32 1
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 2
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-NEXT:    [[E4:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[GEP3]], i32 0, i32 1
// CHECK-NEXT:    [[GEP5:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 0, i32 0
// CHECK-NEXT:    [[GEP6:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 0, i32 2
// CHECK-NEXT:    [[GEP7:%.*]] = getelementptr inbounds [[STRUCT_DERIVED]], ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[GEP5]], align 8
// CHECK-NEXT:    store double [[TMP0]], ptr [[GEP1]], align 8
// CHECK-NEXT:    [[BF_LOAD:%.*]] = load i24, ptr [[E4]], align 1
// CHECK-NEXT:    [[BF_SHL:%.*]] = shl i24 [[BF_LOAD]], 9
// CHECK-NEXT:    [[BF_ASHR:%.*]] = ashr i24 [[BF_SHL]], 9
// CHECK-NEXT:    [[BF_CAST:%.*]] = sext i24 [[BF_ASHR]] to i32
// CHECK-NEXT:    [[TMP1:%.*]] = trunc i32 [[BF_CAST]] to i24
// CHECK-NEXT:    [[BF_LOAD8:%.*]] = load i24, ptr [[E]], align 1
// CHECK-NEXT:    [[BF_VALUE:%.*]] = and i24 [[TMP1]], 32767
// CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i24 [[BF_LOAD8]], -32768
// CHECK-NEXT:    [[BF_SET:%.*]] = or i24 [[BF_CLEAR]], [[BF_VALUE]]
// CHECK-NEXT:    store i24 [[BF_SET]], ptr [[E]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[GEP6]], align 4
// CHECK-NEXT:    store float [[TMP2]], ptr [[GEP2]], align 4
// CHECK-NEXT:    [[D9:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[B]], i32 0, i32 0
// CHECK-NEXT:    [[D10:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP3:%.*]] = load double, ptr [[D10]], align 1
// CHECK-NEXT:    store double [[TMP3]], ptr [[D9]], align 1
// CHECK-NEXT:    [[E11:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[B]], i32 0, i32 1
// CHECK-NEXT:    [[E12:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[BF_LOAD13:%.*]] = load i24, ptr [[E12]], align 1
// CHECK-NEXT:    [[BF_SHL14:%.*]] = shl i24 [[BF_LOAD13]], 9
// CHECK-NEXT:    [[BF_ASHR15:%.*]] = ashr i24 [[BF_SHL14]], 9
// CHECK-NEXT:    [[BF_CAST16:%.*]] = sext i24 [[BF_ASHR15]] to i32
// CHECK-NEXT:    [[TMP4:%.*]] = trunc i32 [[BF_CAST16]] to i24
// CHECK-NEXT:    [[BF_LOAD17:%.*]] = load i24, ptr [[E11]], align 1
// CHECK-NEXT:    [[BF_VALUE18:%.*]] = and i24 [[TMP4]], 32767
// CHECK-NEXT:    [[BF_CLEAR19:%.*]] = and i24 [[BF_LOAD17]], -32768
// CHECK-NEXT:    [[BF_SET20:%.*]] = or i24 [[BF_CLEAR19]], [[BF_VALUE18]]
// CHECK-NEXT:    store i24 [[BF_SET20]], ptr [[E11]], align 1
// CHECK-NEXT:    [[F:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[B]], i32 0, i32 2
// CHECK-NEXT:    [[F21:%.*]] = getelementptr inbounds nuw [[STRUCT_BFIELDS]], ptr [[REF_TMP]], i32 0, i32 2
// CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[F21]], align 1
// CHECK-NEXT:    store float [[TMP5]], ptr [[F]], align 1
// CHECK-NEXT:    ret void
//
void call11(Derived D) {
  BFields B = (BFields)D;
}

struct Empty {
};

// cast to an empty struct
// CHECK-LABEL: define hidden void @_Z6call12v(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[I:%.*]] = alloca <4 x i32>, align 4
// CHECK-NEXT:    [[E:%.*]] = alloca [[STRUCT_EMPTY:%.*]], align 1
// CHECK-NEXT:    store <4 x i32> <i32 1, i32 2, i32 3, i32 4>, ptr [[I]], align 4
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i32(ptr align 1 [[E]], ptr align 1 @__const._Z6call12v.E, i32 1, i1 false)
// CHECK-NEXT:    ret void
//
void call12() {
  int4 I = {1,2,3,4};
  Empty E = (Empty)I;
}

struct MoreBFields {
  int A;
  uint64_t B: 60;
  float C;
  uint16_t D: 10;
  uint16_t E: 6;
  int : 32;
  double F;
  int : 8;
  uint G;
};

// more complicated bitfield case
// get the gep for the struct.
// D and E share the same field index
// store int A into field A
// store int A in bitField B, do necessary conversions
// store int A into field C
// store int A into bitfield D
// store int A into bitfield E;
// store int A into field F
// store int A into field G
// CHECK-LABEL: define hidden void @_Z6call13i(
// CHECK-SAME: i32 noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MBF:%.*]] = alloca [[STRUCT_MOREBFIELDS:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_MOREBFIELDS]], align 1
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0
// CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[GEP]], i32 0, i32 1
// CHECK-NEXT:    [[D:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[GEP]], i32 0, i32 3
// CHECK-NEXT:    [[E:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[GEP]], i32 0, i32 3
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 2
// CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 5
// CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 7
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP1]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-NEXT:    [[BF_LOAD:%.*]] = load i64, ptr [[B]], align 1
// CHECK-NEXT:    [[BF_VALUE:%.*]] = and i64 [[CONV]], 1152921504606846975
// CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i64 [[BF_LOAD]], -1152921504606846976
// CHECK-NEXT:    [[BF_SET:%.*]] = or i64 [[BF_CLEAR]], [[BF_VALUE]]
// CHECK-NEXT:    store i64 [[BF_SET]], ptr [[B]], align 1
// CHECK-NEXT:    [[CONV5:%.*]] = sitofp i32 [[TMP0]] to float
// CHECK-NEXT:    store float [[CONV5]], ptr [[GEP2]], align 4
// CHECK-NEXT:    [[CONV6:%.*]] = trunc i32 [[TMP0]] to i16
// CHECK-NEXT:    [[BF_LOAD7:%.*]] = load i16, ptr [[D]], align 1
// CHECK-NEXT:    [[BF_VALUE8:%.*]] = and i16 [[CONV6]], 1023
// CHECK-NEXT:    [[BF_CLEAR9:%.*]] = and i16 [[BF_LOAD7]], -1024
// CHECK-NEXT:    [[BF_SET10:%.*]] = or i16 [[BF_CLEAR9]], [[BF_VALUE8]]
// CHECK-NEXT:    store i16 [[BF_SET10]], ptr [[D]], align 1
// CHECK-NEXT:    [[CONV11:%.*]] = trunc i32 [[TMP0]] to i16
// CHECK-NEXT:    [[BF_LOAD12:%.*]] = load i16, ptr [[E]], align 1
// CHECK-NEXT:    [[BF_VALUE13:%.*]] = and i16 [[CONV11]], 63
// CHECK-NEXT:    [[BF_SHL:%.*]] = shl i16 [[BF_VALUE13]], 10
// CHECK-NEXT:    [[BF_CLEAR14:%.*]] = and i16 [[BF_LOAD12]], 1023
// CHECK-NEXT:    [[BF_SET15:%.*]] = or i16 [[BF_CLEAR14]], [[BF_SHL]]
// CHECK-NEXT:    store i16 [[BF_SET15]], ptr [[E]], align 1
// CHECK-NEXT:    [[CONV16:%.*]] = sitofp i32 [[TMP0]] to double
// CHECK-NEXT:    store double [[CONV16]], ptr [[GEP3]], align 8
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP4]], align 4
// CHECK-NEXT:    [[A17:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 0
// CHECK-NEXT:    [[A18:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A18]], align 1
// CHECK-NEXT:    store i32 [[TMP1]], ptr [[A17]], align 1
// CHECK-NEXT:    [[B19:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 1
// CHECK-NEXT:    [[B20:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[BF_LOAD21:%.*]] = load i64, ptr [[B20]], align 1
// CHECK-NEXT:    [[BF_CLEAR22:%.*]] = and i64 [[BF_LOAD21]], 1152921504606846975
// CHECK-NEXT:    [[BF_LOAD23:%.*]] = load i64, ptr [[B19]], align 1
// CHECK-NEXT:    [[BF_VALUE24:%.*]] = and i64 [[BF_CLEAR22]], 1152921504606846975
// CHECK-NEXT:    [[BF_CLEAR25:%.*]] = and i64 [[BF_LOAD23]], -1152921504606846976
// CHECK-NEXT:    [[BF_SET26:%.*]] = or i64 [[BF_CLEAR25]], [[BF_VALUE24]]
// CHECK-NEXT:    store i64 [[BF_SET26]], ptr [[B19]], align 1
// CHECK-NEXT:    [[C:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 2
// CHECK-NEXT:    [[C27:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 2
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[C27]], align 1
// CHECK-NEXT:    store float [[TMP2]], ptr [[C]], align 1
// CHECK-NEXT:    [[D28:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 3
// CHECK-NEXT:    [[D29:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 3
// CHECK-NEXT:    [[BF_LOAD30:%.*]] = load i16, ptr [[D29]], align 1
// CHECK-NEXT:    [[BF_CLEAR31:%.*]] = and i16 [[BF_LOAD30]], 1023
// CHECK-NEXT:    [[BF_LOAD32:%.*]] = load i16, ptr [[D28]], align 1
// CHECK-NEXT:    [[BF_VALUE33:%.*]] = and i16 [[BF_CLEAR31]], 1023
// CHECK-NEXT:    [[BF_CLEAR34:%.*]] = and i16 [[BF_LOAD32]], -1024
// CHECK-NEXT:    [[BF_SET35:%.*]] = or i16 [[BF_CLEAR34]], [[BF_VALUE33]]
// CHECK-NEXT:    store i16 [[BF_SET35]], ptr [[D28]], align 1
// CHECK-NEXT:    [[E36:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 3
// CHECK-NEXT:    [[E37:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 3
// CHECK-NEXT:    [[BF_LOAD38:%.*]] = load i16, ptr [[E37]], align 1
// CHECK-NEXT:    [[BF_LSHR:%.*]] = lshr i16 [[BF_LOAD38]], 10
// CHECK-NEXT:    [[BF_LOAD39:%.*]] = load i16, ptr [[E36]], align 1
// CHECK-NEXT:    [[BF_VALUE40:%.*]] = and i16 [[BF_LSHR]], 63
// CHECK-NEXT:    [[BF_SHL41:%.*]] = shl i16 [[BF_VALUE40]], 10
// CHECK-NEXT:    [[BF_CLEAR42:%.*]] = and i16 [[BF_LOAD39]], 1023
// CHECK-NEXT:    [[BF_SET43:%.*]] = or i16 [[BF_CLEAR42]], [[BF_SHL41]]
// CHECK-NEXT:    store i16 [[BF_SET43]], ptr [[E36]], align 1
// CHECK-NEXT:    [[F:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 5
// CHECK-NEXT:    [[F44:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 5
// CHECK-NEXT:    [[TMP3:%.*]] = load double, ptr [[F44]], align 1
// CHECK-NEXT:    store double [[TMP3]], ptr [[F]], align 1
// CHECK-NEXT:    [[G:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[MBF]], i32 0, i32 7
// CHECK-NEXT:    [[G45:%.*]] = getelementptr inbounds nuw [[STRUCT_MOREBFIELDS]], ptr [[REF_TMP]], i32 0, i32 7
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[G45]], align 1
// CHECK-NEXT:    store i32 [[TMP4]], ptr [[G]], align 1
// CHECK-NEXT:    ret void
//
void call13(int A) {
  MoreBFields MBF = (MoreBFields)A;
}

struct Inner {
  int Z;
  int Y : 25;
};

struct Outer {
  int A;
  Inner I;
};

// show usage of "extra" gep for struct containing bitfield
// showing real usage of "extra gep". need Inner struct to generate access of its bitfield.
// CHECK-LABEL: define hidden void @_Z6call14i(
// CHECK-SAME: i32 noundef [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[O:%.*]] = alloca [[STRUCT_OUTER:%.*]], align 1
// CHECK-NEXT:    [[REF_TMP:%.*]] = alloca [[STRUCT_OUTER]], align 1
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds [[STRUCT_OUTER]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [[STRUCT_OUTER]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[Y:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER:%.*]], ptr [[GEP1]], i32 0, i32 1
// CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [[STRUCT_OUTER]], ptr [[REF_TMP]], i32 0, i32 1, i32 0
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr [[GEP2]], align 4
// CHECK-NEXT:    [[BF_LOAD:%.*]] = load i32, ptr [[Y]], align 1
// CHECK-NEXT:    [[BF_VALUE:%.*]] = and i32 [[TMP0]], 33554431
// CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i32 [[BF_LOAD]], -33554432
// CHECK-NEXT:    [[BF_SET:%.*]] = or i32 [[BF_CLEAR]], [[BF_VALUE]]
// CHECK-NEXT:    store i32 [[BF_SET]], ptr [[Y]], align 1
// CHECK-NEXT:    [[A3:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[O]], i32 0, i32 0
// CHECK-NEXT:    [[A4:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[REF_TMP]], i32 0, i32 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A4]], align 1
// CHECK-NEXT:    store i32 [[TMP1]], ptr [[A3]], align 1
// CHECK-NEXT:    [[I:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[O]], i32 0, i32 1
// CHECK-NEXT:    [[Z:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER]], ptr [[I]], i32 0, i32 0
// CHECK-NEXT:    [[I5:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[Z6:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER]], ptr [[I5]], i32 0, i32 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[Z6]], align 1
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[Z]], align 1
// CHECK-NEXT:    [[Y7:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER]], ptr [[I]], i32 0, i32 1
// CHECK-NEXT:    [[I8:%.*]] = getelementptr inbounds nuw [[STRUCT_OUTER]], ptr [[REF_TMP]], i32 0, i32 1
// CHECK-NEXT:    [[Y9:%.*]] = getelementptr inbounds nuw [[STRUCT_INNER]], ptr [[I8]], i32 0, i32 1
// CHECK-NEXT:    [[BF_LOAD10:%.*]] = load i32, ptr [[Y9]], align 1
// CHECK-NEXT:    [[BF_SHL:%.*]] = shl i32 [[BF_LOAD10]], 7
// CHECK-NEXT:    [[BF_ASHR:%.*]] = ashr i32 [[BF_SHL]], 7
// CHECK-NEXT:    [[BF_LOAD11:%.*]] = load i32, ptr [[Y7]], align 1
// CHECK-NEXT:    [[BF_VALUE12:%.*]] = and i32 [[BF_ASHR]], 33554431
// CHECK-NEXT:    [[BF_CLEAR13:%.*]] = and i32 [[BF_LOAD11]], -33554432
// CHECK-NEXT:    [[BF_SET14:%.*]] = or i32 [[BF_CLEAR13]], [[BF_VALUE12]]
// CHECK-NEXT:    store i32 [[BF_SET14]], ptr [[Y7]], align 1
// CHECK-NEXT:    ret void
//
void call14(int A) {
  Outer O = (Outer)A;
}
